version: '3'
services:
  webapp:
    container_name: webapp
    build:
      context: .
      args:
        - access_token=${ACCESS_TOKEN}
        - branch=${BRANCH}
    env_file: 
      - ./.env
    ports:
      - '3000:3000'